### ISSUE TITLE
filter-vs-layer-pruning

### ISSUE THREAD

**Issue by Lovegood-1** [selkerdawy/one-shot-layer-pruning#1]
Hi, 
I have read another paper of your :To filter prune, or to layer prune, that is the question. Is there a code for https://github.com/selkerdawy/filter-vs-layer-pruning? 
The link is not available.

**Comment by selkerdawy** [comment]
Hi,

Thanks for your interest, the repo is public now and we are yet to update it with trained models and experiments.

**Comment by Lovegood-1** [comment]
It is so nice of you! Thanks!
